assignment_final/omg/config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get '/members', to: 'members#index', as: 'members'
  get '/members/:id', to: 'members#show', as: 'member'
  get '/members/:id/new', to: 'comments#new', as: 'comment_new'
  post '/members/:id/create', to: 'comments#create', as: 'comment_create'
  delete '/members/:id/:cid', to: 'comments#destroy', as: 'comment_delete' 


  get '/albums', to: 'albums#index', as: 'albums'
  get '/lyrics', to: 'lyrics#index', as: 'lyrics'

  # resources :comments
end

assignment_final/omg/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

assignment_final/omg/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :member
end

assignment_final/omg/app/models/member.rb
class Member < ApplicationRecord
    # mount_uploader :image, ImageUploader
    has_many :comments
end

assignment_final/omg/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
    def index
        render 'index'
    end
end

assignment_final/omg/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

assignment_final/omg/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    # def index
    #     render 'index'
    # end

    def new
        @comment = Comment.new
    end

    def create
        @member = Member.find(params[:id])
        @comment = @member.comments.create(comment_params)

        redirect_to member_path(@member)
    end

    def destroy
        @member = Member.find(params[:id]) 
        @comment = @member.comments.find(params[:cid])
        @comment.destroy
        redirect_to member_path(params[:id])
    end

    private
    def comment_params
        params.require(:comment).permit(:content)
    end
end

assignment_final/omg/app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        render 'index'
    end
end

assignment_final/omg/app/controllers/lyrics_controller.rb
class LyricsController < ApplicationController
    def index
        render 'index'
    end
end

assignment_final/omg/app/controllers/members_controller.rb
class MembersController < ApplicationController
    def index
        @members = Member.all
        render 'index'
    end

    def show
        @member = Member.find(params[:id])
    end

end

assignment_final/omg/app/helpers/albums_helper.rb
module AlbumsHelper
end

assignment_final/omg/app/helpers/application_helper.rb
module ApplicationHelper
end

assignment_final/omg/app/helpers/comments_helper.rb
module CommentsHelper
end

assignment_final/omg/app/helpers/home_helper.rb
module HomeHelper
end

assignment_final/omg/app/helpers/lyrics_helper.rb
module LyricsHelper
end

assignment_final/omg/app/helpers/members_helper.rb
module MembersHelper
end

assignment_final/omg/app/views/albums/index.html.erb
<!DOCTYPE html>
	<html>
		<head>
			<title>Albums</title>
	        <%= stylesheet_link_tag "albums", media: "all" %>
		</head>
		
		<body>
            <h1><%= link_to "Oh My Girl", '/', class:"title" %></h1>
				<div class="img-container">
                    <%= image_tag "cupid.jpeg", :alt => "", :style => "width: 220px; height: 220px;" %>
                    <%= image_tag "closer.jpeg", :alt => "", :style => "width: 220px; height: 220px;" %>
                    <%= image_tag "liarliar.jpeg", :alt => "", :style => "width: 220px; height: 220px;" %>
                    <%= image_tag "windyday.jpeg", :alt => "", :style => "width: 220px; height: 220px;" %>
                    <%= image_tag "a-ing.jpeg", :alt => "", :style => "width: 220px; height: 220px;" %>	          
                    <%= image_tag "coloringbook.jpeg", :alt => "", :style => "width: 220px; height: 220px;" %>
                    <%= image_tag "secretgarden.jpeg", :alt => "", :style => "width: 220px; height: 220px;" %>
                    <%= image_tag "firework.jpeg", :alt => "", :style => "width: 220px; height: 220px;" %>
                    <%= image_tag "thefifthseason.jpeg", :alt => "", :style => "width: 220px; height: 220px;" %>
                    <%= image_tag "bungee.jpeg", :alt => "", :style => "width: 220px; height: 220px;" %>	
				</div>
		
				<div class="titles">
					Cupid, Closer, <span style="color: #F08080">Liar Liar</span>, Windy Day, A-ing,
					<strong>Coloring Book</strong>, Secret Garden, Firework, <em>The Fifth Season</em>, Bungee
				</div>

		</body>
					
	</html>

assignment_final/omg/app/views/home/index.html.erb
<!DOCTYPE html>
	<html>
		<head>
			<title>OMG zzang</title>
	        <%= stylesheet_link_tag "index", media: "all" %>
		</head>
		
		<body>
            <h1><%= link_to "Oh My Girl", '/', class:"title" %></h1>
			<nav>
				<ul>
					<li>
                        <%= link_to  "멤버 소개", 'members', class:"nav-item" %>
					</li>
					<li>
                        <%= link_to  "앨범", 'albums', class:"nav-item"%>
					</li>
					<li>
                        <%= link_to  "활동", 'lyrics', class:"nav-item" %>
					</li>
					<li>
                        <%= link_to  "공식 팬카페", 'http://cafe.daum.net/-ohmygirl', target:"_blank", class:"nav-item"%>
					</li>
				</ul>
			</nav>
			<div class="video" >
				<iframe
					width="560"
					height="315"
					src="https://www.youtube.com/embed/cHjrl0JVRik"
					frameborder="0"
					allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
					allowfullscreen
				></iframe>
			</div>

		</body>
					
	</html>

assignment_final/omg/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Omg</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

assignment_final/omg/app/views/lyrics/index.html.erb
<!DOCTYPE html>
	<html>
		<head>
			<title>OMG zzang</title>
		</head>
		
		<body>
            <h1><%= link_to "Oh My Girl", '/', class:"title" %></h1>
			<div class="prefix">더쿠 맘대로 뽑은 best 가사들</div>
			<ol type="1">
				<li >
					<p>remember me do you remember me<br>
					날 바라보던 너의 눈에 비친 내 모습이 참 맘에 들었는데<br>
					나도 몰랐던 날 알게 해준 널 만났던 건 참 행운인 걸 yeah</p>
					<p>다시 이런 우연은 없을거라 넌 늘 새기듯 말했지<br>

					거슬러 틀려 봐봐 돌아가도 결국 그 자리잖아<br>
					oh 돌아와도 뻔한데 oh 왜 머릿속에<br>
					oh<strong>네가 눈이 부시게 퍼져 disappear</strong></p>

					<p>(*)사랑스런 그때의 너 우리의 기억이 아른거리고<br>
					조금 이른 사랑얘긴 저 별들처럼 나를 비추고<br>
					눈을 감으면 remember me 시작되는 magic<br>
					remember me 처음이라서 remember me<br>
					마냥 좋았던 do you remember 그때 불꽃놀이</p>

					<p>모래알 같은 기억들 속에서도<br>
					<span style="color: #F08080">난 단숨에 널 찾아낼 수 있어</span><br>
					너에겐 내가 어떻게 남았는지 궁금해졌어<br>
					난 어땠을까 yeah</p>

					<p>사실 그때 나의 세상은 너와 나 밖에 없어서<br>
					안녕 한동안 감기보다 더 아팠지<br>
					oh 너를 그려보았네 oh 까만 하늘에<br>
					oh 다시 눈부시도록 <span style="color: #F08080"><em>펑펑</em></span> disappear</p>

					(*)<br>
				
					<p>remember me 그때 우리<br>
					불꽃놀이 같던 둘만의 하늘빛<br>
					잊지 말아줘 ah ah no no<br>
					아주 더 오래 지나도 <em>가끔 날 그려줘</em></p>

					<p>태어나서 본 것 중에 제일 커다란 꽃<br>
					오직 둘만의 축제<br>
					계절이 되돌아와도 가장 아름다웠던<br>
					시간 너머로 remember me 띄워보는 편지<br>
					remember me 네가 있어서 remember me<br>
					마냥 설렜던 do you remember 그때 불꽃놀이<br>
					눈을 감으면 remember me 시작되는 magic<br>
					remember me 처음이라서 remember me<br>
					마냥 좋았던 do you remember 그때 불꽃놀이<br>
					remember me remember me</p>
				</li>
				<li>
					<p>어딘가 달라 보였던 화창했던 오후였을까<br>
					아마 나의 맘에 뭔가 툭 떨어진 것 같은데<br>
					이상하게 설레던 내 맘</p>

					<p>얼굴에 뭐가 묻은 건 아닌데 뚫어져라 빤히 날 보는데<br>
					아무 말도 못 하고 눈만 깜박였지<br>
					그때 갑자기 비 냄새가 났던 것 같아</p>

					<p>혹시 넌 기억하니<br>
					한 방울 두 방울 떨어질 때에 그곳에 서 있던 너와 나<br>
					잔뜩 몰려온 구름 색깔도 어딘가 오묘한 느낌이었지</p>

					<p>기억해 서로를 눈에 담고서 느리게 느리게 흘러가던 순간을<br>
					나의 맘속에 예쁜 <span style="color: #F08080">파스텔 빛 비가 처음 내리던</span> 그 날을</p>

					<p>어쩌지 나 어떡하지 이미 쏟아진 내 마음은<br>
					담을 수도 없는데 그래도 웃음이 나는 걸<br>
					이런 감정을 숨길 수 없어</p>

					<p>두 손이 포개진 것도 아닌데 아주 살짝 스쳤을 뿐인데<br>
					너무너무 놀라서 굳어버렸었지<br>
					그때 갑자기 비 냄새가 났던 것 같아</p>

					<p>혹시 넌 기억하니<br>
					<strong>한 방울 두 방울</strong> 떨어질 때에 그곳에 서 있던 너와 나<br>
					잔뜩 몰려온 구름 색깔도 어딘가 오묘한 느낌이었지</p>

					<p>기억해 서로를 눈에 담고서 느리게 느리게 흘러가던 순간을<br>
					나의 맘속에 예쁜 파스텔 빛 비가 처음 내리던 그 날을<br>
					기억해 서로를 눈에 담고서 느리게 느리게 흘러가던 순간을<br>
					나의 맘속에 <span style="color: #F08080"><em>예쁜 파스텔 빛 비가 처음 내리던 그 날을</em></span></p>

					<p>넌 테두리 너머까지 촉촉이 내리고 천천히 번지고<br>
					그날의 공기도 촉감도 작은 그 무엇도 잊을 수 없어</p>

					<p>난 그때 그 모든 게 너무 선명해 그곳에 서 있던 너와 나<br>
					<em>잔뜩 몰려온 구름 색깔</em>도 어딘가 오묘한 느낌이었지<br>
					기억해 서로를 눈에 담고서 느리게 느리게 흘러가던 순간을<br>
					나의 맘속에 예쁜 파스텔 빛 비가 처음 내리던 그 날을<br>
					the story of our love</p>

				</li>
				<li>	
					<p><strong><em>폭풍전야</em></strong> ah<br>
					숨죽여 Do it, Do it now woo-<br>
					날따라와 ah 움직여 Do it, Do it<br>
					시간이 된 것 같아 yeah</p>

					<p>부드러운 껍질을 벗겨내면 (강인한 마음과)<br>
					날카로운 눈빛엔 굳은 결심이 어려<br>
					이 심장이 뛰는게 넌 느껴지니<br>
					오래 기다려온 순간이야 Do it</p>

					<p>정말로 원하는 건 잊어본 적이 없지 지난 모든 아침, 잠들던 순간까지<br>
					소중하게 지켜온 너와 나의 모든 것을 여기 지금이야</p>

					<p>(*)너와 난 때를 기다리고 덮쳐 뜨겁게 뒤집고 흔들어놔<br>
					성난 파도처럼 삼켜 깃발을 꽂아봐 승리를 sing forever<br>
					<span style="color: #F08080">눈부신 하늘 너와 난 shine forever</span></p>
					그러니 모두 Attention Do it, Do it</p>

					<p>하얀 빛을 위해 어둠은 찾아와<br>
					일찍 마주했을 뿐이라고<br>
					그것은 심연의 빛도 어둠의 결실 맺고<br>
					그 어느것도 될 수 없는 것이라고</p>

					<p>Oh, Do it, Do it</p>

					<p>이 안개는 언젠가는 걷힐 테니<br>
					불안 속에 갇혀있지 말고 Do it</p>

					<p>낯설고 새로운걸 겁내본적은 없지<br>
					모든 위험들이 날 크게 만들 테니<br>
					소중하게 지켜온 너와나의 모든 것을 여기 지금이야</p>

					(*)<br>

					<p>잘 봐 널 둘러싸던 벽들이 <em>도미노처럼 무너지는 모습을<em><br>
					귀를 기울여보면 들리니 반짝이는 너의 이름</p>

					<p>그러니 Do it, Do it<br>
					Salute, 모두 다 Salute<br>
					승부를 던져 yeah 날 따라와</p>

					(*)<br>

					<p>Salute 모두 다 Salute<br>
					<span style="color: #F08080">승부를 던져</span><br>
					Attention Do it, Do it</p>
				</li>
			</ol>
		</body>
	</html>

assignment_final/omg/app/views/members/index.html.erb
<!DOCTYPE html>
	<html>
		<head>
			<title>Members</title>
	        <%= stylesheet_link_tag "members", media: "all" %>

		</head>
		
		<body>
            <h1><%= link_to "Oh My Girl", '/', class:"title" %></h1>
			<table>
				<thead>
					<tr>
						<th>image</th>
						<th>name</th>
						<th>b-day</th>
						<th>position</th>
					</tr>
				</thead>
				<tbody>
                    <% @members.each do |member| %>
                        <tr>
                            <td><%= link_to image_tag(member.image), member_path(id: member.id) %></td>
                            <td><%= member.name %></td>
                            <td><%= member.bday %></td>
                            <td><%= member.position %></td>
                        </tr>
                    <% end %>
				</tbody>
			</table>
		</body>
					
	</html>

assignment_final/omg/app/views/members/show.html.erb
<head>
    <title>Members</title>
    <%= stylesheet_link_tag "member", media: "all" %>

</head>

<body>
    <h1><%= link_to "Oh My Girl", '/', class:"title" %></h1>
    <%= link_to  "뒤로 가기", members_path, class:'back-btn' %>
    <div class="profile-container">
        <%= image_tag @member.image, class: 'profile-img' %>
        <div class="profile-box">
            <span><%= @member.name %> | </span>
            <span><%= @member.bday %> | </span>
            <span><%= @member.position %></span>
        </div>
    </div>

    <div class="new-comment">
        <%= form_for :comment, url: "/members/#{@member.id}/create" do |f| %>
            <%= f.label :comment, class:'comment-label' %>
            <%= f.text_area :content, class:'comment-input' %>
            <%= f.submit '댓글 달기', class:'submit-btn' %>
        <% end %>
    </div>
    
    <div class="comment-list">
        <% @member.comments.each do |comment| %>
            <div class="comment-box">
                <%= comment.content %>
                <%= link_to image_tag('trash.png', style: 'width: 18px; height: auto;'), comment_delete_path(@member.id, comment.id), method: :delete %>
            </div>
        <% end %>
    </div>

</body>